### ISSUE TITLE
A comment on this sample

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-aspnetcore-webapi-sample#9]
The sample makes use of Fiddler, so it might be nice to find a few words on how to set this tool up to match the experience shown at 

![image](https://cloud.githubusercontent.com/assets/2712405/24208879/262ec610-0efb-11e7-81d2-8ff1863acbdf.png)

**Comment by jerriep** [comment]
@adriatic The use of Fiddler in the sample was merely for illustrative purposes to demonstrate that the JWT middleware will download the RS256 keys automatically from the Auth0 website.

Adding any more detail around Fiddler is outside of the scope of the sample.

Please refer to the Fiddler website if you require more information on how to configure it:
http://www.telerik.com/fiddler

**Comment by adriatic** [comment]
@jerriep Please allow me to make something clear - with a very few exceptions, my comments are not meant to be a sign that I need additional clarifications, but rather that I am trying to point out what is likely to be perceived as insufficiently explained by an average visitor. 

It is disappointing to find myself assessed as someone who needs information on Fiddler (I actually wrote a very similar tool long time ago). Alternatively, I would think that you do not find my attempted services as useful, so I will "cease and desist".

**Comment by jerriep** [comment]
@adriatic Please feel free to continue contributing your thoughts. But understand that we need to assess your ideas and then based on that make a decision whether adding the information you suggested will contribute or distract from the tutorial.

In this case, - as pointed out previously - any discussion around Fiddler is outside of the scope of the quickstart. The screenshot you referenced is there merely to prove that the keys are being downloaded automatically from the Auth0 website. My thoughts are therefore that any further explanation of Fiddler will distract from the actual purpose of the tutorial.

> It is disappointing to find myself assessed as someone who needs information on Fiddler

I have no idea as to your knowledge of Fiddler or the lack thereof. I base my response purely on your request "a few words on how to set this tool up to match the experience shown". Based on that my impression was that you - personally - require assistance on how to set this up. If you consider this an insult of your own abilities, then I apologise. It was not meant as such. It was meant as trying to assist someone who, in my view, clearly asked for assistance.

**Comment by adriatic** [comment]
> It was meant as trying to assist someone who, in my view, clearly asked for assistance.

That conclusion is incorrect: from the getgo, my participation was driven by my desire to help you with a view of an Auth0 novice, who has a very positive view on Auth0 and does not mind spending the time to type a lot, if such information could be of use. At no point would I even dare to use our "relationship" (one document writer to another) as a means to get technical support for me personally; that would not be ethical, and I have several friends on Auth0 support team as well as very friendly support team that I would use in such case.

Yes, we do have a miscommunication - my attempt to help was interpreted to be asking for help. For that I can only blame myself as the size of this error reflect very poorly on my communication skills - and consequently my ability to help. 

> But understand that we need to assess your ideas and then based on that make a decision whether adding the information you suggested will contribute or distract from the tutorial.

The possibility that my ideas could distract the flow of the tutorial (note that directly reflects on skills as a technical writer) completely demotivates me from offering a single word.

**Comment by jerriep** [comment]
The reason why the entire [Signature Validation section](https://auth0.com/docs/quickstart/backend/aspnet-core-webapi#signature-validation) was added was because the feedback we were indeed getting on the quickstart was that people believed the signature validation was not done properly because they could not see any place where the signature of the JWT was being validated.

That section was added to prove that the signature was indeed being validated, and the Fiddler screenshot was added to prove that the RS256 keys were indeed being downloaded from Auth0 and they did not have to do it manually (as the JWT middleware on many other platforms require).

Since that section was added we have not gotten feedback again on possible lack of signature validation. So that side note clearly resolved that question in the mind of readers.

Yours is the first ever feedback I received on further clarification on configuring Fiddler. Should I get more feedback like this I will consider adding links to help developers get going with Fiddler. For now, based on the current feedback, I do not deem this necessary.

I therefore keep to my original assessment that adding any more information on Fiddler will distract from the intended purpose of the tutorial - which is to help developers configure Auth0 in their ASP.NET APIs.

**Comment by adriatic** [comment]
It seems that I acted as a primadona - but that was not my intent and I apologize if that was your perception. Other than trying to help by stating my own interpretation of various texts, I do not have any other agendas. You are perfectly correct when saying

> I therefore keep to my original assessment that adding any more information on Fiddler will distract from the intended purpose of the tutorial - which is to help developers configure Auth0 in their ASP.NET APIs.

and I fully respect that.

**Comment by jerriep** [comment]
No worries :)

**Comment by adriatic** [comment]
Thank you :smile:
